version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR Public...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k4z2i6m8
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-flask-app .
      - docker tag my-flask-app:latest public.ecr.aws/k4z2i6m8/my-flask-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR Public...
      - docker push public.ecr.aws/k4z2i6m8/my-flask-app:latest
artifacts:
  files:
    - '**/*'
