version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - yum install -y aws-cli

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k4z2i6m8
      - echo Verifying ECS cluster and service existence...
      - aws ecs describe-clusters --cluster-names my-flask-app-cluster 
      - aws ecs describe-services --cluster my-flask-app-cluster --services my-flask-app-service  # Replace with your actual service name

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t public.ecr.aws/k4z2i6m8/my-flask-app .
      - docker tag public.ecr.aws/k4z2i6m8/my-flask-app:latest public.ecr.aws/k4z2i6m8/my-flask-app:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push public.ecr.aws/k4z2i6m8/my-flask-app:latest
      - docker push public.ecr.aws/k4z2i6m8/my-flask-app:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Updating ECS service with new image...
      - aws ecs update-service --cluster my-flask-app-cluster --service my-flask-app-service --force-new-deployment --desired-count 1 --task-definition family:my-flask-app-container 

artifacts:
  files:
    - imagedefinitions.json
