version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - yum install -y aws-cli
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k4z2i6m8
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t public.ecr.aws/k4z2i6m8/my-flask-app:$CODEBUILD_RESOLVED_SOURCE_VERSION .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/k4z2i6m8/my-flask-app:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' public.ecr.aws/k4z2i6m8/my-flask-app:$CODEBUILD_RESOLVED_SOURCE_VERSION > imageDetail.json
artifacts:
  files:
    - appspec.yaml
    - taskdef.json
    - imageDetail.json
